In [1]:
import numpy as np

numpy array

In [2]:
mylist=[20,30,40]

In [3]:
np.array(mylist)

array([20, 30, 40])

In [4]:
type(np.array(mylist))

numpy.ndarray

In [5]:
matrixlist=[[10,20,30],[20,30,40],[30,40,50]]

In [6]:
np.array(matrixlist)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

arrange

In [7]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

zeros: sıfırlardan oluşan dizi

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

linspace

In [17]:
np.linspace(0,20,5)
#5 sayı seç ve aralarındaki mesafe aynı olsun

array([ 0.,  5., 10., 15., 20.])

eye köşegeni 1 diğerlerini 0 yapar

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

random

In [21]:
np.random.randn(4)

array([-0.07430096, -0.57484341, -0.15202784, -0.04593689])

In [23]:
np.random.randn(3,2)

array([[-1.78393542, -0.40024035],
       [-0.35132488, -1.93159044],
       [-1.87675673, -0.10671042]])

In [25]:
np.random.randint(1,10)
#son sayı alınmaz iki değer arasından rondom sayı seçilir

4

In [26]:
np.random.randint(5,300,10)

array([ 99,  68,  90, 229, 177, 182, 128, 263,  98,  11])

numpy dizi methodlari

In [31]:
mynumpydizi=np.arange(0,30)

In [32]:
mynumpydizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
myrandomdizi= np.random.randint(0,100,20)

In [34]:
myrandomdizi

array([50, 28, 68, 99, 58, 59, 63,  0,  2, 34, 72, 51, 79, 99, 29, 55, 62,
       12, 24, 11])

In [36]:
mynumpydizi.reshape(5,6)
#30 tane sayıyı böler ama tam bölen sayı seçmeliyiz eşit paylaştırılmalı

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [37]:
mynumpydizi.max()

29

In [38]:
myrandomdizi.max()

99

In [39]:
myrandomdizi.min()

0

In [40]:
#en büyük sayı hangi indexte
myrandomdizi.argmax()

3

In [41]:
myrandomdizi.argmin()

7

In [43]:
reshapedizi=mynumpydizi.reshape(5,6)

In [45]:
reshapedizi.shape
#kestiğimiz dizi kaça kaçlık bir matris bunu döndürür

(5, 6)