In [1]:
import numpy as np

In [2]:
myarray= np.arange(0,15)

In [3]:
myarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
myarray[5]

5

In [5]:
myarray[3:5]

array([3, 4])

In [6]:
myarray[3:8]=-5

In [7]:
myarray

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [9]:
myarray2=np.arange(0,24)

In [10]:
myarray2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [13]:
alicidizi=myarray2[4:9]

In [14]:
alicidizi

array([4, 5, 6, 7, 8])

In [15]:
type(alicidizi)

numpy.ndarray

In [16]:
alicidizi[:]=700

In [17]:
alicidizi

array([700, 700, 700, 700, 700])

In [19]:
myarray2

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [20]:
# alicidizi elemanlarını değiştirirken myarray2 nin de değişti

In [21]:
ornekdizi=np.arange(0,24)

In [22]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [23]:
ornekdizikopyası=ornekdizi.copy()

In [24]:
ornekdizikopyasıslicing=ornekdizikopyası[3:6]

In [25]:
ornekdizikopyasıslicing

array([3, 4, 5])

In [26]:
ornekdizikopyasıslicing[:]=800

In [27]:
ornekdizikopyasıslicing

array([800, 800, 800])

In [28]:
ornekdizikopyası

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [29]:
ornekdizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

matrix

In [30]:
mylist=[[10,20,30],[20,30,40],[40,50,60]]

In [31]:
mymatrixarray=np.array(mylist)

In [32]:
mymatrixarray

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [33]:
mymatrixarray[1][2]

40

In [34]:
mymatrixarray[1,2]

40

In [35]:
mymatrixarray[1:,2]
#1 ve 2.satiri getirir onların 2.sutunlarındaki elemanlarını getirir

array([40, 60])

In [36]:
mymatrixarray[:,2]

array([30, 40, 60])

In [38]:
mymatrixarray[:,2:]

array([[30],
       [40],
       [60]])

In [39]:
newlist=[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [40]:
newmatrix=np.array(newlist)

In [41]:
newmatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
newmatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

operasyonlar

In [46]:
newarray= np.random.randint(1,100,20)

In [47]:
newarray

array([83, 58, 93, 94, 58, 25, 92, 48, 43,  6, 33, 10, 55, 11, 26, 63, 87,
       70, 49, 99])

dizi içinde belli sayıları çekme:

In [48]:
newarray > 24

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True])

In [49]:
sonucdizi= newarray > 24

In [50]:
sonucdizi

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False,  True, False,  True,  True,  True,  True,
        True,  True])

In [51]:
newarray[sonucdizi]

array([83, 58, 93, 94, 58, 25, 92, 48, 43, 33, 55, 26, 63, 87, 70, 49, 99])

In [52]:
sondizi=np.arange(0,24)

In [53]:
sondizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [54]:
sondizi+sondizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])